name: "release-action"

on:
  push:
    tags:
      - "v*"

jobs:
    release-action:
        name: "Create Release"
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.1.1
              with:
                fetch-depth: 0
                ref: ${{ github.event.repository.default_branch }}

            - name: Install ZIP
              run: sudo apt install zip
    
            - name: Bundle files
              run: |
                rm -rf ./.github ./.vscode ./.git
                zip -r ./${{ github.event.repository.name }}.zip ./
        
            - name: Create Release
              uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                title: ${{ github.ref_name }}
                repo_token: '${{ secrets.GITHUB_TOKEN }}'
                prerelease: false
                files: ${{ github.event.repository.name }}.zip